# Generated by Django 4.2.4 on 2023-09-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Timg',
            field=models.ImageField(upload_to='photo'),
        ),
    ]
