# Generated by Django 4.2.4 on 2023-09-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_alter_team_timg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
