# Generated by Django 4.2.4 on 2023-09-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tname', models.CharField(max_length=250)),
                ('Timg', models.ImageField(upload_to='photo')),
                ('Tdesc', models.TextField()),
            ],
        ),
    ]
